# Generated by Django 5.1.5 on 2025-01-31 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('end_date', models.DateTimeField(default=None, null=True, verbose_name='Дата окончания')),
                ('status', models.TextField(choices=[('active', 'Активен'), ('completed', 'Завершен'), ('paused', 'Приостановлен')], default='active', verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('priority', models.BooleanField(verbose_name='Приоритет')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('end_date', models.DateTimeField(default=None, null=True, verbose_name='Дата окончания')),
                ('status', models.TimeField(choices=[('active', 'Активна'), ('completed', 'Завершена'), ('paused', 'Приостановлена')], default='active', verbose_name='Статус')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='main.project', verbose_name='Проект')),
            ],
        ),
    ]
