# Generated by Django 5.1.5 on 2025-01-31 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_project_options_alter_task_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.TextField(choices=[('high', 'Высокий'), ('medium', 'Средний'), ('low', 'Низкий')], verbose_name='Приоритет'),
        ),
    ]
