# Generated by Django 5.1.5 on 2025-01-31 22:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_task_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['priority', '-pk']},
        ),
        migrations.AddField(
            model_name='project',
            name='moders',
            field=models.ManyToManyField(related_name='mods', to=settings.AUTH_USER_MODEL, verbose_name='Важные Шишки'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.TextField(choices=[('progress', 'Активна'), ('completed', 'Завершена'), ('not_started', 'Не_начата')], default='not_started', verbose_name='Статус'),
        ),
    ]
