# Generated by Django 5.1.5 on 2025-01-31 22:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_task_options_project_moders_alter_task_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='requests',
            field=models.ManyToManyField(related_name='reqs', to=settings.AUTH_USER_MODEL, verbose_name='Запросы'),
        ),
    ]
